#!/usr/bin/env python3
"""Validate or deliberately generate persona-native Claude and Codex adapters."""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
import tomllib
from pathlib import Path
from urllib.parse import urlsplit

MARKER = "# Generated by Personas persona-native-sync.py"
SOURCE = "# source-agents: "
SENSITIVE = re.compile(r"(?:api[_-]?key|token|secret|password|authorization|cookie)", re.I)
LITERAL = re.compile(r"(?:sk-[A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9_-]{12,})")


def fail(message: str) -> None:
    raise ValueError(message)


def persona_data(persona: Path) -> tuple[str, str, Path]:
    agents = (persona / "AGENTS.md").resolve()
    if not agents.is_file(): fail(f"missing {agents}")
    lines = agents.read_text(encoding="utf-8").splitlines()
    if not any(line.startswith("# ") for line in lines): fail("AGENTS.md needs an H1")
    description = next((line[1:].strip() for line in lines if line.startswith(">")), None)
    if not description: fail("AGENTS.md needs an opening blockquote")
    slug = re.sub(r"[^a-z0-9]+", "-", persona.name.lower()).strip("-")
    if not slug: fail("persona directory does not produce a slug")
    return slug, description, agents


def credential_free(value: object, key: str = "") -> None:
    if SENSITIVE.search(key):
        if isinstance(value, str) and re.fullmatch(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}", value): return
        fail(f"credential literal is unsupported: {key}")
    if isinstance(value, str) and LITERAL.search(value): fail("credential literal is unsupported")
    if isinstance(value, dict):
        for nested_key, nested in value.items(): credential_free(nested, str(nested_key))
    elif isinstance(value, list):
        for nested in value: credential_free(nested, key)


def load_mcp_payload(persona: Path) -> tuple[dict[str, object], list[str]]:
    source = persona / ".mcp.json"
    if not source.exists(): return {}, []
    payload = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(payload, dict): fail(".mcp.json must be an object")
    if set(payload) - {"mcpServers", "mcp_servers", "codexMcpServers"}: fail(".mcp.json has unsupported top-level fields")
    servers = payload.get("mcpServers", payload.get("mcp_servers"))
    if not isinstance(servers, dict): fail(".mcp.json needs an mcpServers object")
    names = payload.get("codexMcpServers", [])
    if not isinstance(names, list) or not all(isinstance(name, str) and name for name in names): fail(".mcp.json codexMcpServers must be a list of nonempty names")
    if len(names) != len(set(names)): fail(".mcp.json codexMcpServers must be unique")
    return servers, names


def selected_codex_mcps(servers: dict[str, object], names: list[str]) -> dict[str, dict[str, object]]:
    result: dict[str, dict[str, object]] = {}
    for name in names:
        if name not in servers: fail(f"Codex MCP opt-in names an unavailable binding: {name}")
        raw = servers[name]
        if not isinstance(raw, dict): fail(f"MCP {name} must be an object")
        credential_free(raw)
        kind = raw.get("type", "stdio")
        allowed = {"command", "args", "env", "type"} if kind == "stdio" else {"type", "url"}
        extra = set(raw) - allowed
        if extra: fail(f"MCP {name} has unsupported fields: {', '.join(sorted(extra))}")
        if kind == "stdio":
            if not isinstance(raw.get("command"), str): fail(f"MCP {name} needs a command")
            if "args" in raw and not (isinstance(raw["args"], list) and all(isinstance(x, str) for x in raw["args"])): fail(f"MCP {name} args must be strings")
            if "env" in raw and not (isinstance(raw["env"], dict) and all(isinstance(k, str) and isinstance(v, str) for k, v in raw["env"].items())): fail(f"MCP {name} env must map strings to strings")
        elif kind in {"streamable-http", "http"}:
            if not isinstance(raw.get("url"), str) or not raw["url"].startswith(("https://", "http://")): fail(f"MCP {name} needs an HTTP url")
            parsed = urlsplit(raw["url"])
            if parsed.username is not None or parsed.password is not None:
                fail(f"MCP {name} HTTP url must not contain credentials")
        else: fail(f"MCP {name} transport {kind!r} is unsupported")
        result[name] = raw
    return result


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def codex_mcp(mcps: dict[str, dict[str, object]]) -> str:
    blocks = []
    for name, item in mcps.items():
        lines = [f"[mcp_servers.{toml_string(name)}]"]
        if item.get("type", "stdio") == "stdio":
            lines.append(f"command = {toml_string(item['command'])}")
            if item.get("args"): lines.append("args = [" + ", ".join(toml_string(x) for x in item["args"]) + "]")
            if item.get("env"): lines.append("env = {" + ", ".join(f"{toml_string(k)} = {toml_string(v)}" for k, v in item["env"].items()) + "}")
        else: lines.append(f"url = {toml_string(item['url'])}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def rendered(slug: str, description: str, agents: Path, mcps: dict[str, dict[str, object]]) -> tuple[str, str, str]:
    meta = f"{MARKER}\n{SOURCE}{json.dumps(str(agents))}\n"
    claude = f"---\nname: {slug}\ndescription: {toml_string(description)}\n---\n\n{meta}\nRead and follow {agents}.\n"
    mcp = codex_mcp(mcps)
    codex = f"{meta}name = {toml_string(slug)}\ndescription = {toml_string(description)}\ndeveloper_instructions = {toml_string(f'Read and follow {agents}.')}\n"
    if mcp: codex += f"\n{mcp}\n"
    return claude, codex, f"{meta}\n{mcp}\n"


def owner(content: str) -> str | None:
    for line in content.splitlines():
        if line.startswith(SOURCE):
            try:
                return json.loads(line[len(SOURCE):])
            except json.JSONDecodeError:
                return None
    return None


def legacy_owner(content: str) -> str | None:
    match = re.search(r"^Read and follow (.+)\.$", content, re.MULTILINE)
    if match: return match.group(1)
    match = re.search(r"^developer_instructions = (.+)$", content, re.MULTILINE)
    if not match: return None
    try:
        instruction = json.loads(match.group(1))
    except json.JSONDecodeError:
        return None
    prefix = "Read and follow "
    return instruction[len(prefix):-1] if isinstance(instruction, str) and instruction.startswith(prefix) and instruction.endswith(".") else None


def disposition(path: Path, content: str, agents: Path) -> str:
    if not path.exists():
        return "drift"
    existing = path.read_text(encoding="utf-8")
    if existing == content:
        return "current"
    if MARKER not in existing[:300]:
        fail(f"refusing to overwrite unmarked or other-source file: {path}")
    recorded_owner = owner(existing)
    if SOURCE in existing:
        if recorded_owner == str(agents):
            return "drift"
    elif legacy_owner(existing) == str(agents):
        return "drift"
    if path.name.startswith("persona-") and path.suffix == ".toml":
        fail(f"legacy profile ownership is unknown; review and move aside {path} before applying")
    fail(f"refusing to overwrite generated adapter owned by another persona: {path}")


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary_path = Path(temporary.name)
        try:
            temporary.write(content)
            temporary.close()
            temporary_path.replace(path)
        finally:
            temporary_path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--persona", required=True, type=Path)
    parser.add_argument("--runtime", choices=("claude", "codex", "all"), default="all")
    parser.add_argument("--codex-artifact", choices=("profile", "agent", "all"), default="all")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--codex-mcp", action="append", default=[], metavar="NAME")
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")))
    args = parser.parse_args()
    try:
        persona = args.persona.resolve()
        slug, description, agents = persona_data(persona)
        if args.runtime in ("codex", "all"):
            servers, declared_names = load_mcp_payload(persona)
            mcps = selected_codex_mcps(servers, [*declared_names, *args.codex_mcp])
        else:
            mcps = {}
        claude, codex, profile = rendered(slug, description, agents, mcps)
        tomllib.loads(codex)
        tomllib.loads(profile)
        targets: list[tuple[Path, str]] = []
        if args.runtime in ("claude", "all"):
            targets.append((args.claude_home / "agents" / f"{slug}.md", claude))
        if args.runtime in ("codex", "all"):
            if args.codex_artifact in ("agent", "all"):
                targets.append((args.codex_home / "agents" / f"{slug}.toml", codex))
            if args.codex_artifact in ("profile", "all"):
                targets.append((args.codex_home / f"persona-{slug}.config.toml", profile))
        states = [(path, content, disposition(path, content, agents)) for path, content in targets]
        legacy = args.codex_home / "agents" / f"persona-{slug}.config.toml"
        prune_legacy = args.runtime in ("codex", "all") and args.codex_artifact in ("agent", "all") and legacy.exists()
        if prune_legacy:
            legacy_content = legacy.read_text(encoding="utf-8")
            if MARKER not in legacy_content[:300]:
                fail(f"refusing to remove unmarked legacy profile: {legacy}")
            recorded_owner = owner(legacy_content)
            known_owner = recorded_owner == str(agents) if SOURCE in legacy_content else legacy_owner(legacy_content) == str(agents)
            if not known_owner:
                fail(f"legacy adapter ownership is unknown; review and move aside {legacy} before applying")
        for index, (path, content, state) in enumerate(states):
            if args.apply and state == "drift":
                try:
                    write(path, content)
                except OSError as error:
                    completed = ", ".join(str(done) for done, _, status in states[:index] if status == "drift") or "none"
                    remaining = ", ".join(str(todo) for todo, _, status in states[index:] if status == "drift") or "none"
                    fail(f"write failed: {error}; completed: {completed}; remaining: {remaining}")
            print(f"{state if not args.apply or state == 'current' else 'updated'} {path}")
        if prune_legacy:
            if args.apply:
                legacy.unlink()
            print(f"{'removed' if args.apply else 'stale'} {legacy}")
        print("Claude path access must permit the live AGENTS.md; global Claude permissions are unchanged.")
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
