#!/usr/bin/env python3
"""Report or apply native Claude and Codex subagents that load a persona folder."""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
import tomllib
from pathlib import Path
from urllib.parse import parse_qsl, urlsplit

MARKER = "# Generated by Personas persona-native-sync.py"
SOURCE = "# source-agents: "
COLORS = ("red", "blue", "green", "yellow", "purple", "orange", "pink", "cyan")
SENSITIVE = re.compile(r"(?:api[_-]?key|token|secret|password|authorization|cookie)", re.I)
# Values under a credential-like key that cannot hold a secret: an env reference or a boolean flag.
NOT_SECRET = re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}|true|false", re.I)
LITERAL = re.compile(r"(?:sk-[A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9_-]{12,})")


def fail(message: str) -> None:
    raise ValueError(message)


def strings(value: object) -> bool:
    return isinstance(value, list) and all(isinstance(item, str) for item in value)


def persona_slug(persona: Path) -> str:
    return re.sub(r"[^a-z0-9]+", "-", persona.name.lower()).strip("-") or fail("persona directory does not produce a slug")


def credential_free(value: object, key: str = "") -> None:
    if SENSITIVE.search(key) and not (isinstance(value, str) and NOT_SECRET.fullmatch(value)):
        fail(f"credential literal is unsupported: {key}")
    if isinstance(value, str) and LITERAL.search(value): fail("credential literal is unsupported")
    if isinstance(value, dict):
        for nested_key, nested in value.items(): credential_free(nested, str(nested_key))
    elif isinstance(value, list):
        for nested in value: credential_free(nested, key)


def agent_mcps(persona: Path) -> dict[str, dict[str, object]]:
    source = persona / ".mcp.json"
    if not source.exists(): return {}
    payload = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(payload, dict) or set(payload) - {"mcpServers", "agentMcpServers"}: fail(".mcp.json must be an object with only mcpServers and agentMcpServers")
    servers, names = payload.get("mcpServers", {}), payload.get("agentMcpServers", [])
    if not isinstance(servers, dict): fail(".mcp.json mcpServers must be an object")
    if not strings(names) or not all(names) or len(names) != len(set(names)): fail(".mcp.json agentMcpServers must list unique server names")
    selected = {}
    for name in names:
        raw = servers.get(name)
        if not isinstance(raw, dict): fail(f"agentMcpServers names an unavailable server: {name}")
        credential_free(raw)
        kind = raw.get("type", "stdio")
        if kind == "stdio":
            env = raw.get("env", {})
            if set(raw) - {"type", "command", "args", "env"} or not isinstance(raw.get("command"), str) or not strings(raw.get("args", [])) \
                    or not (isinstance(env, dict) and strings(list(env.values()))):
                fail(f"MCP {name} needs only a string command, string args, and string env")
        elif kind in ("http", "streamable-http", "sse"):
            if set(raw) - {"type", "url", "oauth"} or not isinstance(raw.get("url"), str) or not raw["url"].startswith(("https://", "http://")):
                fail(f"MCP {name} needs only type, an HTTP url, and optional oauth")
            oauth = raw.get("oauth", {})
            if not isinstance(oauth, dict): fail(f"MCP {name} oauth must be an object")
            if extra := sorted(set(oauth) - {"clientId", "callbackPort"}):
                fail(f"MCP {name} oauth {', '.join(extra)} is unsupported; only clientId and callbackPort may be set, and credentials stay out of .mcp.json")
            if not isinstance(oauth.get("clientId", ""), str) or type(oauth.get("callbackPort", 0)) is not int:
                fail(f"MCP {name} oauth needs a string clientId and an integer callbackPort")
            url = urlsplit(raw["url"])
            if url.username is not None or url.password is not None: fail(f"MCP {name} HTTP url must not contain credentials")
            if any(SENSITIVE.search(key) for part in (url.query, url.fragment) for key, _ in parse_qsl(part, keep_blank_values=True)):
                fail(f"MCP {name} HTTP url must not contain credential parameters")
        else: fail(f"MCP {name} transport {kind!r} is unsupported")
        selected[name] = {"type": kind} | raw
    return selected


def toml_value(value: object) -> str:
    if isinstance(value, list): return "[" + ", ".join(map(toml_value, value)) + "]"
    if isinstance(value, dict): return "{" + ", ".join(f"{json.dumps(k, ensure_ascii=False)} = {toml_value(v)}" for k, v in value.items()) + "}"
    return json.dumps(value, ensure_ascii=False)


def codex_gap(server: dict[str, object]) -> str | None:
    """Name why Codex cannot run a server Claude can, or None when it can."""
    if server["type"] == "sse": return "sse transport is unsupported"
    if "oauth" in server: return "oauth config is Claude-only"
    return None


def rendered(persona: Path, description: str, color: str | None, mcps: dict[str, dict[str, object]]) -> tuple[str, str]:
    agents, quote = persona / "AGENTS.md", lambda value: json.dumps(value, ensure_ascii=False)
    meta = f"{MARKER}\n{SOURCE}{quote(str(agents))}\n"
    body = f"You are the persona defined in {agents}. Read and follow it. Resolve its relative paths (skills/, user/, tools/) from {persona}."
    front = [f"name: {quote(persona_slug(persona))}", f"description: {quote(description)}", *([f"color: {quote(color)}"] if color else [])]
    front += ["mcpServers:", *(f"  - {quote(name)}: {quote(server)}" for name, server in mcps.items())] if mcps else []
    claude = "---\n" + "\n".join(front) + f"\n---\n\n{meta}\n{body}\n"
    codex = meta + "".join(f"{key} = {quote(value)}\n" for key, value in (("name", persona_slug(persona)), ("description", description), ("developer_instructions", body)))
    for name, server in mcps.items():
        if codex_gap(server): continue
        fields = {key: value for key, value in server.items() if key != "type"}
        codex += f"\n[mcp_servers.{quote(name)}]\n" + "".join(f"{key} = {toml_value(value)}\n" for key, value in fields.items())
    tomllib.loads(codex)
    return claude, codex


def owned(path: Path, agents: Path) -> str | None:
    """Return the existing adapter text if this persona owns it; refuse anything else."""
    if not path.exists(): return None
    existing = path.read_text(encoding="utf-8")
    recorded = next((line[len(SOURCE):] for line in existing.splitlines() if line.startswith(SOURCE)), None)
    if MARKER not in existing or recorded != json.dumps(str(agents), ensure_ascii=False):
        fail(f"refusing to overwrite a file this persona does not own; review and move aside {path}")
    return existing


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary_path = Path(temporary.name)
        try:
            temporary.write(content)
            temporary.close()
            temporary_path.replace(path)
        finally:
            temporary_path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--persona", required=True, type=Path)
    parser.add_argument("--runtime", choices=("claude", "codex", "all"), default="all")
    parser.add_argument("--color", choices=COLORS, help="Claude agent color; preserved from the existing adapter when omitted")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--claude-home", type=Path, default=Path.home() / ".claude")
    parser.add_argument("--codex-home", type=Path, default=Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")))
    args = parser.parse_args()
    try:
        persona = args.persona.resolve()
        agents = persona / "AGENTS.md"
        lines = agents.read_text(encoding="utf-8").splitlines() if agents.is_file() else fail(f"missing {agents}")
        description = next((line[1:].strip() for line in lines if line.startswith(">")), None) or fail("AGENTS.md needs an opening blockquote")
        slug = persona_slug(persona)
        targets = {"claude": args.claude_home / "agents" / f"{slug}.md", "codex": args.codex_home / "agents" / f"{slug}.toml"}
        targets = {runtime: path for runtime, path in targets.items() if args.runtime in (runtime, "all")}
        existing = {runtime: owned(path, agents) for runtime, path in targets.items()}
        preserved = re.search(r'^color: "?([a-z]+)"?$', (existing.get("claude") or "").split("\n---", 1)[0], re.M)
        color = args.color or (preserved.group(1) if preserved and preserved.group(1) in COLORS else None)
        mcps = agent_mcps(persona)
        content = dict(zip(("claude", "codex"), rendered(persona, description, color, mcps)))
        if "codex" in targets:
            for name, server in mcps.items():
                if reason := codex_gap(server): print(f"skipped {name} for codex: {reason}")
        for runtime, path in targets.items():
            state = "current" if existing[runtime] == content[runtime] else "drift"
            if args.apply and state == "drift":
                write(path, content[runtime])
                state = "updated"
            print(f"{state} {path}")
        return 0
    except (OSError, ValueError, json.JSONDecodeError, tomllib.TOMLDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
